fix(temp-storage): move workingCache to temporary storage (fixes #1136)
Lumieducation/Lumi pull request #1727
Opened 2021-07-27 15:59 UTC by JPSchellenberg

Hey,

I started to work on the issue that the old content is not cleaned up by saving it into the `app.getPath('temp')` folder. Is this a viable way? @sr258

2021-07-27 16:12 UTC, JPSchellenberg commented
I remove the old workingCache directory during the setup process. What do you think?

2021-07-27 16:55 UTC, sr258 requested changes
The temporary files in the "real" temporary directory aren't deleted as well. In LumiPlayer I've done it like this:

```
app.on('will-quit', (event) => {
    log.debug(`Deleting temporary directory: ${tmpDir}`);
    fsExtra.removeSync(tmpDir);
});
````

2021-07-27 16:55 UTC, sr258 commented on server/src/main.ts
> -                process.env.USERDATA || app.getPath('userData')
I think we should reuse the serverConfig from above if possible

2021-07-27 16:55 UTC, sr258 commented on server/src/main.ts
> +        process.env.TEMPDATA || app.getPath('temp')
The temp path is generic and not app specific. In the player, I've appended a directory:
`const tmpDir = path.join(app.getPath('temp'), 'lumiplayer')`

2021-07-27 16:55 UTC, sr258 commented on server/src/boot/setup.ts
> +        const workingCachePath = path.join(
The same should be done for the temporary files

2021-08-02 13:30 UTC, sr258 approved these changes
Everything looks fine. I think it makes sense to include this in 0.8.0 after all.

2021-08-02 13:32 UTC, merged